version: '3.8'
services:
  backend:
    build:
      context: ./Food-Delivery-upstream/backend
      dockerfile: ../../Dockerfile-backend
    image: devops_food_delivery_infra-backend:latest
    ports:
      - "4001:4000"
    depends_on:
      - db
    environment:
      - PORT=4000
      - MONGO_URL=mongodb://root:root@db:27017/food_delivery?authSource=admin
    deploy:
      replicas: 2
  frontend:
    build:
      context: ./Food-Delivery-upstream/frontend
      dockerfile: ../../Dockerfile-frontend
    image: devops_food_delivery_infra-frontend:latest
    ports:
      - "3002:3000"
    depends_on:
      - backend
    deploy:
      replicas: 2
  db:
    image: mongo:6
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - data:/data/db
    deploy:
      replicas: 1
volumes:
  data:
